# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"basic_matmul": "01_basic_network.ipynb",
         "allclose": "01_basic_network.ipynb",
         "dot_prod_matmul": "01_basic_network.ipynb",
         "broadcast_mat_mul": "01_basic_network.ipynb",
         "matmul": "01_basic_network.ipynb"}

modules = ["feedforward.py"]

doc_url = "https://your_github_username.github.io/dl_foundations_study/"

git_url = "https://github.com/your_github_username/dl_foundations_study/tree/master/"

def custom_doc_links(name): return None
